name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy-github-page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          HUSKY_SKIP_INSTALL=1 npm ci
          npm run build:gitpage
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist

  build-docker-image-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          npm ci
          npm run build
      - name: Publish Docker
        uses: elgohr/Publish-Docker-Github-Action@2.11
        with:
          name: mrtree/tecentimgs
          username: ${{ secrets.DOCKER_HUB_NAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          dockerfile: Dockerfile
      - name: SSH & Update Conteiner
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TECENT_HOST }}
          username: ${{ secrets.TECENT_USERNAME }}
          key: ${{ secrets.TECENT_PASSWORD }}
          script: |
            sudo docker container stop vueApp
            sudo docker container rm  vueApp
            sudo docker image rm mrtree/tecentimgs
            sudo docker image pull mrtree/tecentimgs
            sudo docker run -p 3000:80 -d --name vueApp mrtree/tecentimgs
