name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          BUILD_SCRIPT: npm install && npm run build

  publish-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Publish Docker
        uses: elgohr/Publish-Docker-Github-Action@2.11
        with:
          # The name of the image you would like to push
          name: vue-site-example
          # The login username for the registry
          username: ${{ secrets.DOCKER_HUB_NAME }}
          # The login password for the registry
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          # Use registry for pushing to a custom registry
          registry: mrtree/tecentimgs
          # Use snapshot to push an additional image
          # snapshot: # optional
          # Use dockerfile when you would like to explicitly build a Dockerfile
          dockerfile: Dockerfile
          # Use workdir when you would like to change the directory for building
          # workdir: # optional
          # Use buildargs when you want to pass a list of environment variables as build-args
          # buildargs: # optional
          # Use cache when you have big images, that you would only like to build partially
          # cache: # optional
          # Use tag_names when you want to push tags/release by their git name
          # tag_names: # optional
