name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          HUSKY_SKIP_INSTALL=1 npm ci
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist

      - name: Publish Docker
        uses: elgohr/Publish-Docker-Github-Action@2.11
        with:
          name: mrtree/tecentimgs
          username: ${{ secrets.DOCKER_HUB_NAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          # Use registry for pushing to a custom registry
          # registry: mrtree/tecentimgs
          # Use snapshot to push an additional image
          # snapshot: # optional
          # Use dockerfile when you would like to explicitly build a Dockerfile
          dockerfile: Dockerfile
          # Use workdir when you would like to change the directory for building
          # workdir: # optional
          # Use buildargs when you want to pass a list of environment variables as build-args
          # buildargs: # optional
          # Use cache when you have big images, that you would only like to build partially
          # cache: # optional
          # Use tag_names when you want to push tags/release by their git name
          # tag_names: # optional
